# Theme
include ryoku.conf

# Font
font_family             JetBrains Mono
bold_font               auto
italic_font             auto
bold_italic_font        auto
font_size               11.5

# Window
window_padding_width    8
background_opacity      0.94

# Cursor
cursor_shape                    block
cursor_blink_interval           0
cursor_trail                    1
cursor_trail_decay              0.1 0.4
cursor_trail_start_threshold    1

# Prevent shell integration from changing the cursor shape
shell_integration               no-cursor

# Tabs
tab_bar_edge                    bottom
tab_bar_style                   fade
tab_fade                        1
active_tab_foreground           #eee7df
active_tab_background           #151815
inactive_tab_foreground         #8f8982
inactive_tab_background         #000000

# Mouse
url_style                       straight

# Notifications
notify_on_cmd_finish            never

# Bell
enable_audio_bell               no
visual_bell_duration            0
window_alert_on_bell            no
bell_on_tab                     no
