# Ryoku palette

background              #000000
foreground              #cdc4ba

cursor                  #3f8f71
cursor_text_color       #000000

selection_background    #1b3127
selection_foreground    #e7e0d8

url_color               #5fae89

color0                  #0d0f0d
color8                  #585b58

color1                  #c66f6f
color9                  #df8a8a

color2                  #3f8f71
color10                 #65b88f

color3                  #b59b65
color11                 #d0b77a

color4                  #6f91a8
color12                 #8eabc0

color5                  #987aa1
color13                 #b194ba

color6                  #5a9791
color14                 #77b6ae

color7                  #cdc4ba
color15                 #eee7df
