theme[main_bg]="#000000"
theme[main_fg]="#cdc4ba"
theme[title]="#eee7df"
theme[hi_fg]="#65b88f"
theme[selected_bg]="#1b3127"
theme[selected_fg]="#eee7df"
theme[inactive_fg]="#585b58"
theme[graph_text]="#8f8982"
theme[meter_bg]="#151815"
theme[proc_misc]="#8f8982"

theme[cpu_box]="#3f8f71"
theme[mem_box]="#5a9791"
theme[net_box]="#6f91a8"
theme[proc_box]="#987aa1"

theme[div_line]="#151815"

theme[temp_start]="#3f8f71"
theme[temp_mid]="#b59b65"
theme[temp_end]="#c66f6f"

theme[cpu_start]="#3f8f71"
theme[cpu_mid]="#65b88f"
theme[cpu_end]="#b59b65"

theme[free_start]="#3f8f71"
theme[free_mid]="#5a9791"
theme[free_end]="#6f91a8"

theme[cached_start]="#6f91a8"
theme[cached_mid]="#5a9791"
theme[cached_end]="#3f8f71"

theme[available_start]="#3f8f71"
theme[available_mid]="#65b88f"
theme[available_end]="#5a9791"

theme[used_start]="#b59b65"
theme[used_mid]="#c66f6f"
theme[used_end]="#df8a8a"

theme[download_start]="#3f8f71"
theme[download_mid]="#5a9791"
theme[download_end]="#6f91a8"

theme[upload_start]="#6f91a8"
theme[upload_mid]="#987aa1"
theme[upload_end]="#c66f6f"

theme[process_start]="#3f8f71"
theme[process_mid]="#b59b65"
theme[process_end]="#c66f6f"
